// Builds the user's data-export bundle: a single .zip with, per owned project,
// a full JSON snapshot and a rendered PDF report. Reuses the Export Engine V2
// chain (buildExportContent → analyzeExportSnapshot → renderArchitecturePdf) so
// the bundle is byte-for-byte the same data the normal export download produces.
//
// Determinism: every entry is stamped with a fixed date and emitted in a stable
// order (input order, files sorted within a project), so the same project state
// yields an identical archive (mirrors the PDF renderer's determinism pinning).
//
// Diagrams in the PDF: Mermaid only renders in a browser, so callers may pass
// client-captured SVGs (projectId → diagramId → svg). Without them, each PDF
// falls back to the Mermaid source block (the renderer's normal behavior).
import archiverDefault from "archiver";
import type { Archiver } from "archiver";
import { buildExportContent } from "../../exports/exports.engine.js";
import { analyzeExportSnapshot } from "../../exports/analysis/metrics.engine.js";
import { renderArchitecturePdf } from "../../exports/pdf/pdf.renderer.js";

// archiver is a CJS `export =` callable. NodeNext won't TYPE the default import as
// callable, and a runtime require() returns the (non-callable) ESM namespace under
// tsx/esbuild — but the default import IS resolved to the function at runtime. So
// import the default and cast it to the call signature.
const createZipArchive = archiverDefault as unknown as (
  format: string,
  options?: { zlib?: { level?: number } },
) => Archiver;

// Every recognized section, so the bundle is a COMPLETE snapshot (buildExportContent
// includes only requested sections; empty = nothing).
const ALL_SECTIONS = [
  "ARTIFACTS",
  "RELATIONS",
  "DOCUMENTATION",
  "VALIDATION",
  "GRAPH",
  "API_SPECS",
  "DATABASE_MODELS",
  "DIAGRAMS",
  "VERSION_HISTORY",
  "IMPACT_ANALYSIS",
  "TEAM",
];

// Fixed entry timestamp for deterministic archives.
const FIXED_ENTRY_DATE = new Date("2020-01-01T00:00:00Z");

export interface BundleProject {
  id: string;
  name: string;
}

/** projectId → (diagramId → captured SVG markup). */
export type BundleDiagramSvgs = Record<string, Record<string, string>>;

function safeFolder(name: string, id: string): string {
  const base = (name || "project").replace(/[^a-zA-Z0-9._-]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60);
  // Append a short id slice so two same-named projects never collide in the zip.
  return `${base || "project"}-${id.slice(0, 8)}`;
}

function attachDiagramSvgs(content: unknown, svgs?: Record<string, string>): unknown {
  if (!svgs || !content || typeof content !== "object") return content;
  const c = content as { diagrams?: Array<{ id?: string; renderedSvg?: string | null }> };
  if (!Array.isArray(c.diagrams)) return content;
  for (const d of c.diagrams) {
    if (d && d.id && typeof svgs[d.id] === "string") d.renderedSvg = svgs[d.id];
  }
  return content;
}

function readme(projects: BundleProject[]): string {
  const lines = [
    "MINOTAURUS — account data export",
    "",
    "This archive contains, for each project you own, a full JSON snapshot and a",
    "rendered PDF architecture report. JSON is the lossless source of truth; the",
    "PDF is a human-readable report generated from it.",
    "",
    `Projects (${projects.length}):`,
    ...projects.map((p) => `  - ${p.name} → ${safeFolder(p.name, p.id)}/`),
    "",
    "Generated by Minotaurus as part of an account-deletion request.",
  ];
  return lines.join("\n");
}

/**
 * Build the bundle for the given projects. Returns the complete zip as a Buffer
 * (sized for email attachment + direct download). A single project's render
 * failure is isolated: an `<folder>/ERROR.txt` note is written instead of
 * aborting the whole archive.
 */
export async function buildAccountExportZip(
  projects: BundleProject[],
  svgs?: BundleDiagramSvgs,
): Promise<Buffer> {
  const archive = createZipArchive("zip", { zlib: { level: 9 } });
  const chunks: Buffer[] = [];
  archive.on("data", (c: Buffer) => chunks.push(c));
  const finished = new Promise<void>((resolve, reject) => {
    archive.on("end", () => resolve());
    // Warnings (e.g. stat quirks) are non-fatal — log, don't abort the archive.
    archive.on("warning", (err: unknown) => {
      // eslint-disable-next-line no-console
      console.warn("[account-deletion] zip warning", err instanceof Error ? err.message : err);
    });
    archive.on("error", (err: unknown) => reject(err));
  });

  archive.append(readme(projects), { name: "README.txt", date: FIXED_ENTRY_DATE });

  for (const p of projects) {
    const folder = safeFolder(p.name, p.id);
    try {
      const jsonContent = await buildExportContent(p.id, "JSON", ALL_SECTIONS);
      archive.append(JSON.stringify(jsonContent, null, 2), {
        name: `${folder}/${folder}.json`,
        date: FIXED_ENTRY_DATE,
      });

      const pdfContent = attachDiagramSvgs(
        await buildExportContent(p.id, "PDF", ALL_SECTIONS),
        svgs?.[p.id],
      );
      const analysis = analyzeExportSnapshot(pdfContent);
      const pdf = await renderArchitecturePdf({
        content: (pdfContent && typeof pdfContent === "object" ? pdfContent : {}) as never,
        analysis,
        meta: {
          id: p.id,
          format: "PDF",
          sections: ALL_SECTIONS,
          createdAt: FIXED_ENTRY_DATE.toISOString(),
        },
      });
      archive.append(pdf, { name: `${folder}/${folder}.pdf`, date: FIXED_ENTRY_DATE });
    } catch (err) {
      const message = err instanceof Error ? err.message : "unknown error";
      archive.append(`Failed to export this project: ${message}\n`, {
        name: `${folder}/ERROR.txt`,
        date: FIXED_ENTRY_DATE,
      });
    }
  }

  await archive.finalize();
  await finished;
  return Buffer.concat(chunks);
}
